-- TP2/init-scripts/init-ho.sql
CREATE DATABASE IF NOT EXISTS ho;
USE ho;

CREATE TABLE IF NOT EXISTS data (
  id INT AUTO_INCREMENT PRIMARY KEY,
  source VARCHAR(10) NOT NULL,
  name VARCHAR(255) NOT NULL,
  value VARCHAR(255) NOT NULL,
  timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);