version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  mysql-bo1:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bo1
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_bo1_data:/var/lib/mysql 
      - ./init-scripts/init-bo1.sql:/docker-entrypoint-initdb.d/init.sql

  mysql-bo2:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bo2
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_bo2_data:/var/lib/mysql
      - ./init-scripts/init-bo2.sql:/docker-entrypoint-initdb.d/init.sql

  mysql-ho:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ho
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3308:3306"
    volumes:
      - mysql_ho_data:/var/lib/mysql
      - ./init-scripts/init-ho.sql:/docker-entrypoint-initdb.d/init.sql
  api-service:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mysql-bo1
      - mysql-bo2
      - mysql-ho
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      BO1_DB_HOST: mysql-bo1
      BO2_DB_HOST: mysql-bo2
      HO_DB_HOST: mysql-ho
      DB_USER: user
      DB_PASS: password
      API_IP: 127.0.0.1
      API_PORT: 8081
      BO1_PORT: 3306
      BO2_PORT: 3306
      HO_PORT: 3306
      QUEUE_NAME: product_sales_task_queue
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      BO1_DB_NAME: bo1
      BO2_DB_NAME: bo2
      HO_DB_NAME: ho
  ho-consumer:
    build:
      context: .
      dockerfile: ./consumer/Dockerfile
    depends_on:
      - mysql-ho
      - rabbitmq
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: guest
      RABBITMQ_PASS: guest
      DB_HOST: mysql-ho
      DB_USER: user
      DB_PASS: password
      DB_NAME: ho
      QUEUE_NAME: product_sales_task_queue
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
      HO_DB_DSN: user:password@tcp(mysql-ho:3306)/ho?parseTime=true


volumes: 
  mysql_bo1_data:
  mysql_bo2_data:
  mysql_ho_data:
#
#  bo1-consumer:
#    build:
#      context: ./consumers/bo1
#    depends_on:
#      - rabbitmq
#      - mysql-bo1
#    environment:
#      RABBITMQ_HOST: rabbitmq
#      RABBITMQ_PORT: 5672
#      RABBITMQ_USER: guest
#      RABBITMQ_PASS: guest
#      DB_HOST: mysql-bo1
#      DB_USER: user
#      DB_PASS: password
#      DB_NAME: bo1
#
#  bo2-consumer:
#    build:
#      context: ./consumers/bo2
#    depends_on:
#      - rabbitmq
#      - mysql-bo2
#    environment:
#      RABBITMQ_HOST: rabbitmq
#      RABBITMQ_PORT: 5672
#      RABBITMQ_USER: guest
#      RABBITMQ_PASS: guest
#      DB_HOST: mysql-bo2
#      DB_USER: user
#      DB_PASS: password
#      DB_NAME: bo2
#